-- CreateEnum
CREATE TYPE "Category" AS ENUM ('WEB_DEVELOPMENT', 'MOBILE_DEVELOPMENT', 'DATA_SCIENCE', 'MACHINE_LEARNING', 'AI', 'BLOCKCHAIN', 'CLOUD_COMPUTING', 'DEVOPS', 'CYBER_SECURITY', 'IOT', 'AR_VR', 'GAME_DEVELOPMENT', 'MATHEMATICS', 'PHYSICS', 'CHEMISTRY', 'SCIENCE', 'SOFTWARE', 'OTHER');

-- AlterTable
ALTER TABLE "courses" ADD COLUMN     "category" "Category"[];
